.TH LIBFM-PREF-APPS 1 "February 13, 2012"
.SH NAME
libfm-pref-apps \- sets preferred applications for programs based on libfm
.SH SYNOPSIS
.B libfm-pref-apps
.SH SEE ALSO
.BR pcmanfm (1)
.SH AUTHOR
libfm-pref-apps was written by Hong Jen Yee <pcman.tw@gmail.com>.
.PP
This manual page was written by Sergey Slipchenko <faergeek@gmail.com>,
for the Debian project (and may be used by others).
